version: '3.8'

services:
  server:
    image: card-game-server
    ports:
      - 8080:8080
    depends_on:
      - redis
    container_name: web_card-game-server
    environment: 
      - REDIS_HOST=db_redis
      - REDIS_PORT=6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes: 
      - ./data/redis:/data
    container_name: db_redis