
(*) --> ルームの作成
-right-> ルームに参加
-right-> 締め切り
--> スタート
-left-> カードを配る
-left-> カードトレード実施
--> プレイ順番の決定
--> 手番プレイヤーの確定
--> 手番の開始
if プレイヤーがカードが出すかどうか then
    --> [Yes]捨てるカードを宣言して裏向きで場に出す
    if ダウト宣言があるかどうか then
        --> [Yes]カードをオープンする
        if カードが宣言どおりかどうか then
            --> [Yes]手番プレイヤーのカードを捨てる
            --> 宣言者のカードを一枚表にする
            --> 次の手番を手番プレイヤーとする
            --> 場のカードを捨てる
        else
            --> [No]手番プレイヤーの出したカードを表にする
            --> 次の手番をダウト宣言者とする
            --> 手番プレイヤーの確定
        endif
    else
        --> [No]カードを捨てる
    endif
    if カードの枚数がゼロかどうか then
        --> "[Yes]上がり（プレイヤー人数-1）"
        if プレイヤー残り人数が1人かどうか then
            --> [Yes]ゲーム終了
            --> (*)
        else
            --> [No]次のプレイヤーの手番へ
        endif
    else
        --> [No]次のプレイヤーの手番へ
    endif
else
    --> [No]パスをする
    if 【参加人数-1人】が連続でパスしたかどうか then
        --> [Yes]場のカードを捨てる
        --> 次のプレイヤーの手番へ
    else
        --> [No]次のプレイヤーの手番へ
    endif
endif
----> 手番プレイヤーの確定