
(*) --> ルームの作成
--> ルームに参加
--> 締め切り
--> スタート
--> カードシャッフル
--> "（全員）ベット金額の確定"
--> カードを配る
--> オープンカードの決定
--> 手番プレイヤーの確定
if 親のオープンカードがA then
    --> [Yes] "手番プレイヤー (インシュアランス) 確定"
    if ダウンを選択 then
        --> [Yes] "プレイヤーのダウン(インシュアランス)"
        --> "LOSE_HALF:該当プレイヤーのベット金額の半分を減算"
        --> "次のプレイヤーの手番へ（インシュアランス）"
    else
        --> [No] "次のプレイヤーの手番へ（インシュアランス）"
    endif
    if 一人でもプレイヤーが残っている then
        if 親がブラックジャック then
            --> [Yes] 残っているプレイヤーの負け判定
            --> "LOSE_ALL:該当プレイヤーのベット金額の全額を減算"
            --> ゲーム終了
        else
            --> [No] 次の手番プレイヤーの確定
        endif
    else
        --> ゲーム終了
    endif
else
    --> [No] 手番プレイヤーの確定
endif
--> "プレイヤーの手番開始(通常)"
if プレイヤーがプレイ可能 then
    --> プレイヤーの行動決定
    
    if プレイヤーがHit then
        --> [Yes] "プレイヤーのカード枚数+1"
        if プレイヤーのカードの合計値が22以上 then
            --> [Yes] "LOSE_ALL:該当プレイヤーのベット金額の全額を減算"
        else
            --> [No] プレイヤーの行動決定
        endif
    elseif プレイヤーがStand then
        --> [Yes] プレイヤーの手役決定
    elseif プレイヤーがdown then
        --> [Yes] ああああ
    else
        --> AAAA
    endif
else
    --> [No] 次のプレイヤーの手番決定
endif
----> "プレイヤーの手番開始(通常)"